"use client";
import { useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { BarChart3, FileText, Presentation } from "lucide-react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Button, Card, ErrorState, PageHeader, money } from "@/components/shared/ui";
import { type Scenario, type Simulation, taxImpactSimulatorService } from "@/services/tax-impact-simulator.service";
const initial:Scenario={taxableBase:100000,rates:{icms:18,ipi:0,pis:1.65,cofins:7.6,fcp:0,st:0},riskScore:.7,recoverableRate:.5,monthlyVolume:1,implementationCost:25000};
export default function TaxImpactSimulatorPage(){const [current,setCurrent]=useState<Scenario>(initial),[corrected,setCorrected]=useState<Scenario>({...initial,rates:{...initial.rates,icms:12},riskScore:.2}),[name,setName]=useState("Simulação tributária"),[months,setMonths]=useState(12);const query=useQuery({queryKey:["tax-impact-simulations"],queryFn:taxImpactSimulatorService.list});const mutation=useMutation({mutationFn:taxImpactSimulatorService.create,onSuccess:()=>query.refetch()});const latest=mutation.data??query.data?.[0];const update=(scenario:"current"|"corrected",tax:string,value:number)=>{const setter=scenario==="current"?setCurrent:setCorrected;setter(previous=>({...previous,rates:{...previous.rates,[tax]:value}}));};return <><PageHeader title="Tax Impact Simulator" description="Compare o cenário atual ao corrigido e transforme impacto tributário em decisão executiva." action={<Button onClick={()=>mutation.mutate({name,projectionMonths:months,current,corrected})} disabled={mutation.isPending}><BarChart3 size={16}/>{mutation.isPending?"Calculando...":"Simular impacto"}</Button>}/>{mutation.isError&&<ErrorState message="Não foi possível executar a simulação."/>}<div className="grid gap-5 xl:grid-cols-2"><ScenarioCard title="Cenário atual" value={current.taxableBase} rates={current.rates} onBase={v=>setCurrent({...current,taxableBase:v})} onRate={(t,v)=>update("current",t,v)}/><ScenarioCard title="Cenário corrigido" value={corrected.taxableBase} rates={corrected.rates} onBase={v=>setCorrected({...corrected,taxableBase:v})} onRate={(t,v)=>update("corrected",t,v)}/></div><div className="mt-5 flex gap-3"><input className="h-9 rounded-lg border border-slate-200 px-3 text-sm" value={name} onChange={e=>setName(e.target.value)} placeholder="Nome da simulação"/><input className="h-9 w-28 rounded-lg border border-slate-200 px-3 text-sm" type="number" value={months} onChange={e=>setMonths(Number(e.target.value))}/></div>{latest&&<Executive result={latest.result} id={latest.id}/>}</>}
function ScenarioCard({title,value,rates,onBase,onRate}:{title:string;value:number;rates:Scenario["rates"];onBase:(value:number)=>void;onRate:(tax:string,value:number)=>void}){return <Card className="p-5"><h2 className="mb-4 font-bold text-slate-900">{title}</h2><label className="block text-xs font-semibold text-slate-500">Base tributável</label><input className="mt-1 h-10 w-full rounded-lg border border-slate-200 px-3" type="number" value={value} onChange={e=>onBase(Number(e.target.value))}/><div className="mt-4 grid grid-cols-2 gap-3">{["icms","ipi","pis","cofins","fcp","st"].map(tax=><label key={tax} className="text-xs font-semibold uppercase text-slate-500">{tax}<input className="mt-1 h-9 w-full rounded-lg border border-slate-200 px-3 text-sm" type="number" value={rates[tax as keyof typeof rates]??0} onChange={e=>onRate(tax,Number(e.target.value))}/></label>)}</div></Card>}
function Executive({result,id}:{result:Simulation["result"];id:string}){const data=Object.entries(result.current.taxes).map(([tax,current])=>({tax:tax.toUpperCase(),Atual:current,Correto:result.corrected.taxes[tax]}));return <section className="mt-6"><div className="grid gap-4 md:grid-cols-4"><Metric label="Economia projetada" value={money(result.projection)} positive/><Metric label="Recuperação" value={money(result.recovery)}/><Metric label="ROI" value={result.roi==null?"—":`${result.roi}%`}/><Metric label="Redução de risco" value={`${(result.risk.reduction*100).toFixed(0)} p.p.`}/></div><div className="mt-5 grid gap-5 xl:grid-cols-3"><Card className="p-5 xl:col-span-2"><h2 className="mb-4 font-bold text-slate-900">Carga tributária: atual × corrigida</h2><div className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={data}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="tax"/><YAxis/><Tooltip formatter={(value)=>money(Number(value ?? 0))}/><Bar dataKey="Atual" fill="#ef4444" radius={[4,4,0,0]}/><Bar dataKey="Correto" fill="#2563eb" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div></Card><Card className="p-5"><h2 className="font-bold text-slate-900">Material comercial</h2><p className="mt-2 text-sm text-slate-500">Exporte uma proposta executiva com os cenários e o retorno financeiro.</p><div className="mt-5 space-y-2"><Button onClick={()=>taxImpactSimulatorService.download(id,"pdf")} className="w-full" variant="secondary"><FileText size={16}/> Baixar PDF</Button><Button onClick={()=>taxImpactSimulatorService.download(id,"presentation")} className="w-full" variant="secondary"><Presentation size={16}/> Apresentação PPTX</Button></div></Card></div></section>}
function Metric({label,value,positive}:{label:string;value:string;positive?:boolean}){return <Card className="p-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</p><p className={`mt-2 text-xl font-bold ${positive?"text-emerald-700":"text-slate-900"}`}>{value}</p></Card>}
