"use client";
import { useEffect, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { Database, Link2, Plus, RefreshCw } from "lucide-react";
import { Button, Card, ErrorState, PageHeader } from "@/components/shared/ui";
import { consincoService } from "@/services/consinco.service";
import { dataIngestionService, productEntityTypes, type DataIngestionSettings } from "@/services/data-ingestion.service";

const labels: Record<string,string>={MASTER_PRODUCTS_V1:"Produtos",FAMILY_DIVISION_CATEGORY_V1:"Família, divisão e categoria",FAMILY_TAX_PROFILE_V1:"Perfil tributário da família",TAXATION_UF_V1:"Tributação por UF",FAMILY_UF_DEFAULT_RATE_V1:"Alíquota padrão por UF",FAMILY_PACKAGING_V1:"Embalagens",FAMILY_SUPPLIERS_V1:"Fornecedores"};
export default function ConsincoPage(){
 const [name,setName]=useState("Consinco Produção"),[baseUrl,setBaseUrl]=useState(""),[apiKey,setApiKey]=useState("");
 const [companyId,setCompanyId]=useState(()=>typeof window==="undefined"?"":localStorage.getItem("concilia_company_id")??"");
 const [draft,setDraft]=useState<DataIngestionSettings>();
 useEffect(()=>{const refresh=()=>{setCompanyId(localStorage.getItem("concilia_company_id")??"");setDraft(undefined)};window.addEventListener("concilia:company-changed",refresh);return()=>window.removeEventListener("concilia:company-changed",refresh)},[]);
 const connections=useQuery({queryKey:["consinco-connections",companyId],queryFn:consincoService.listConnections});
 const settings=useQuery({queryKey:["data-ingestion-settings",companyId],queryFn:()=>dataIngestionService.settings(companyId),enabled:!!companyId});
 const currentDraft=draft??settings.data;
 const create=useMutation({mutationFn:()=>consincoService.createConnection({name,baseUrl,companyId:companyId||undefined,apiKeyEncrypted:apiKey||undefined}),onSuccess:()=>{setApiKey("");connections.refetch()}});
 const save=useMutation({mutationFn:()=>dataIngestionService.updateSettings(companyId,{connectorDatabaseEnabled:!!currentDraft?.connectorDatabaseEnabled,consincoApiEnabled:!!currentDraft?.consincoApiEnabled,spedEnabled:!!currentDraft?.spedEnabled,catalogReconciliationEnabled:!!currentDraft?.catalogReconciliationEnabled,fiscalValidationEnabled:!!currentDraft?.fiscalValidationEnabled,entityTypes:currentDraft?.entityTypes??[]}),onSuccess:value=>setDraft(value)});
 const extract=useMutation({mutationFn:(connectionId:string)=>dataIngestionService.extractConsincoApi(companyId,connectionId)});
 const reconcile=useMutation({mutationFn:()=>dataIngestionService.reconcile(companyId)});
 const toggle=(key:keyof Pick<DataIngestionSettings,"connectorDatabaseEnabled"|"consincoApiEnabled"|"spedEnabled"|"catalogReconciliationEnabled"|"fiscalValidationEnabled">)=>currentDraft&&setDraft({...currentDraft,[key]:!currentDraft[key]});
 const toggleEntity=(entity:typeof productEntityTypes[number])=>currentDraft&&setDraft({...currentDraft,entityTypes:currentDraft.entityTypes.includes(entity)?currentDraft.entityTypes.filter(item=>item!==entity):[...currentDraft.entityTypes,entity]});
 return <><PageHeader title="Integração Consinco" description="Escolha as origens, modelos de extração e validações utilizadas por cada empresa." />
 {!companyId&&<ErrorState message="Selecione uma empresa no cabeçalho antes de configurar a integração."/>}
 {companyId&&currentDraft&&<Card className="mb-5 p-5"><h2 className="font-bold text-slate-900">Modos de entrada e validação</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{[["connectorDatabaseEnabled","Banco via Connector"],["consincoApiEnabled","API Consinco"],["spedEnabled","Arquivos SPED"],["catalogReconciliationEnabled","Comparar com catálogo central"],["fiscalValidationEnabled","Validação fiscal"]].map(([key,label])=><label key={key} className="flex items-center gap-2 rounded border p-3 text-sm"><input type="checkbox" checked={Boolean(currentDraft[key as keyof DataIngestionSettings])} onChange={()=>toggle(key as Parameters<typeof toggle>[0])}/>{label}</label>)}</div><h3 className="mt-5 text-sm font-bold text-slate-800">Modelos extraídos</h3><div className="mt-2 grid gap-2 md:grid-cols-2">{productEntityTypes.map(entity=><label key={entity} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={currentDraft.entityTypes.includes(entity)} onChange={()=>toggleEntity(entity)}/>{labels[entity]}</label>)}</div><div className="mt-5 flex gap-2"><Button onClick={()=>save.mutate()} disabled={save.isPending||!currentDraft.entityTypes.length}>Salvar configuração</Button><Button variant="secondary" onClick={()=>reconcile.mutate()} disabled={reconcile.isPending}>Reconciliar agora</Button></div>{reconcile.data&&<p className="mt-3 text-sm text-slate-600">{reconcile.data.matched} iguais · {reconcile.data.divergent} divergentes · {reconcile.data.missingInCentral} ausentes no central</p>}</Card>}
 {companyId&&<Card className="mb-5 p-4"><div className="grid gap-3 md:grid-cols-3"><input className="h-10 rounded-lg border px-3 text-sm" value={name} onChange={e=>setName(e.target.value)} placeholder="Nome da conexão"/><input className="h-10 rounded-lg border px-3 text-sm" value={baseUrl} onChange={e=>setBaseUrl(e.target.value)} placeholder="https://api.consinco.exemplo"/><input type="password" className="h-10 rounded-lg border px-3 text-sm" value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder="Chave da API"/></div><Button className="mt-3" onClick={()=>create.mutate()} disabled={!baseUrl||create.isPending}><Plus size={16}/>Nova conexão</Button></Card>}
 {connections.isError?<ErrorState message="Não foi possível carregar as conexões Consinco."/>:<Card className="overflow-hidden"><table className="w-full text-left text-sm"><thead><tr className="bg-slate-50 text-xs uppercase text-slate-500"><th className="p-3">Conexão</th><th className="p-3">Endereço</th><th className="p-3">Situação</th><th className="p-3"/></tr></thead><tbody>{connections.data?.map(connection=><tr key={connection.id} className="border-t"><td className="p-3 font-semibold">{connection.name}</td><td className="p-3 text-slate-500">{connection.baseUrl}</td><td className="p-3">{connection.active?"Ativa":"Inativa"}</td><td className="p-3"><Button variant="ghost" title="Extrair via API" onClick={()=>extract.mutate(connection.id)} disabled={!companyId||!currentDraft?.consincoApiEnabled||extract.isPending}><Database size={16}/></Button><Button variant="ghost" title="Atualizar"><RefreshCw size={16}/></Button></td></tr>)}</tbody></table>{!connections.isLoading&&!connections.data?.length&&<div className="p-10 text-center text-sm text-slate-500"><Link2 className="mx-auto mb-2"/>Nenhuma conexão configurada.</div>}</Card>}</>;
}
