import { api, type ApiResponse } from "./api/client";
export const extractionTypes = [["MASTER_PRODUCTS_V1", "Produtos"], ["FAMILY_DIVISION_CATEGORY_V1", "Classificação"], ["FAMILY_TAX_PROFILE_V1", "Perfil tributário"], ["TAXATION_UF_V1", "Tributação por UF"], ["FAMILY_UF_DEFAULT_RATE_V1", "Alíquotas padrão"], ["FAMILY_PACKAGING_V1", "Embalagens"], ["FAMILY_SUPPLIERS_V1", "Fornecedores"], ["FISCAL_DOCUMENT_ITEMS_V1", "Itens fiscais por documento"], ["PRODUCT_ACCESS_CODES_V1", "Códigos de acesso (GTIN/EAN)"]] as const;
export type ExtractionType = typeof extractionTypes[number][0]; export type ExtractionSummary = { entityType: ExtractionType; total: number; lastReceivedAt: string | null; lastSourceChangedAt: string | null }; export type ExtractionRecord = { id: string; sourceKey: string; sourceChangedAt: string | null; receivedAt: string; payload: Record<string, unknown> }; export type ExtractionPage = { items: ExtractionRecord[]; total: number; page: number; pageSize: number; totalPages: number };
// Campo (e rótulo) usado para a busca por código de cada consulta — espelha as chaves aceitas
// pelo backend em filterableFields (connector-data.controller.ts). Cada entidade tem seu próprio
// identificador natural: produto, família, tributação/documento etc.
export const searchFieldByType: Record<ExtractionType, { field: string; label: string; placeholder: string }> = {
  MASTER_PRODUCTS_V1: { field: "produtoId", label: "Código do produto", placeholder: "Ex.: 964719" },
  FAMILY_DIVISION_CATEGORY_V1: { field: "familia", label: "Código da família", placeholder: "Ex.: 1234" },
  FAMILY_TAX_PROFILE_V1: { field: "familia", label: "Código da família", placeholder: "Ex.: 1234" },
  TAXATION_UF_V1: { field: "tributacao", label: "Nome da tributação", placeholder: "Ex.: ICMS 18%" },
  FAMILY_UF_DEFAULT_RATE_V1: { field: "familia", label: "Código da família", placeholder: "Ex.: 1234" },
  FAMILY_PACKAGING_V1: { field: "familia", label: "Código da família", placeholder: "Ex.: 1234" },
  FAMILY_SUPPLIERS_V1: { field: "familia", label: "Código da família", placeholder: "Ex.: 1234" },
  FISCAL_DOCUMENT_ITEMS_V1: { field: "documento", label: "Chave do documento", placeholder: "Chave de acesso da NF-e" },
  PRODUCT_ACCESS_CODES_V1: { field: "produto", label: "Código do produto", placeholder: "Ex.: 964719" },
};
export const connectorDataService = { summary: async () => (await api.get<ApiResponse<ExtractionSummary[]>>("/connector-data/summary")).data.data, list: async (entityType: ExtractionType, page = 1, pageSize = 50, search?: string) => { const field = searchFieldByType[entityType].field; const params: Record<string, unknown> = {}; if (page !== 1) params.page = page; if (pageSize !== 50) params.pageSize = pageSize; if (search?.trim()) params.filters = JSON.stringify({ [field]: search.trim() }); return (await api.get<ApiResponse<ExtractionPage>>(`/connector-data/${entityType}`, { params: Object.keys(params).length ? params : undefined })).data.data; }, listAll: async (entityType: ExtractionType) => { const first = await connectorDataService.list(entityType, 1, 200); const pages = Array.from({ length: Math.max(0, first.totalPages - 1) }, (_, index) => connectorDataService.list(entityType, index + 2, 200)); const rest = await Promise.all(pages); return [...first.items, ...rest.flatMap(page => page.items)]; }, record: async (id: string) => (await api.get<ApiResponse<ExtractionRecord & { entityType: ExtractionType }>>(`/connector-data/records/${encodeURIComponent(id)}`)).data.data, deleteTenantData: async (password: string, reason?: string) => (await api.delete<ApiResponse<{ tenantId: string; deletedRecords: number; deletedCorrections: number; deletedJobs: number; deletedBatches: number; resetLoads: number; deletedCatalogApprovals: number }>>("/connector-data/tenant-data", { data: { password, reason } })).data.data };
