import { api, type ApiResponse } from "./api/client";
export type RuleSource={authority:string;title:string;url:string;retrievedAt:string};
export type RuleChange={version:string;date:string;type:"CREATED"|"CHANGED"|"DEPRECATED";ruleCodes:string[];description:string;author:string;sources:RuleSource[]};
export type ValidationRule={id:string;name:string;category:"CADASTRAL"|"FISCAL"|"RELATIONSHIP"|"DOCUMENT"|"SPED"|"REFORM";description:string;validation:string;alertCondition:string;expectedResult:string;appliesTo:string[];severity:"CRITICAL"|"HIGH"|"MEDIUM"|"LOW";active:boolean;adjustableByAnalyst?:boolean;effectiveFrom?:string;effectiveTo?:string;sources?:RuleSource[];origin:"OFFICIAL"|"CLIENT"|"RECONCILIATION";version:string;updatedAt?:string;changeLog?:RuleChange[]};
type OfficialRule={code:string;name:string;category:string;description:string;adjustableByAnalyst:boolean;effectiveFrom?:string;effectiveTo?:string;sources:RuleSource[];version:string;updatedAt:string};
type SuggestedRule={id:string;code:string;name:string;description:string;category:string;active:boolean;status:string;version:number;sourceUrl:string;detectedAt:string;validation?:string;expectedResult?:string;reviewReason?:string};
type OfficialCatalog={version:string;rules:OfficialRule[];changeLog:RuleChange[];adjustments:Array<{id:string;version?:number;ruleCode:string;name:string;reason:string;effectiveFrom:string;effectiveTo?:string;active?:boolean;evidenceUrl?:string;criteria?:Record<string,unknown>;expected?:Record<string,unknown>;updatedAt?:string}>;suggestions:SuggestedRule[]};
const appliesTo:Record<string,string[]>={NCM_FORMAT:["0200","TIPI","Cadastro do produto"],DOCUMENT_CONTEXT:["0000","C100","A100","D100"],CFOP_DIRECTION:["C170","C190","C175","A170","D190"],ICMS_CODE_REGIME:["C170","C190","E110"],PIS_COFINS_CST_DIRECTION:["C170","C175","A170","D101","D105","F100","M105","M505"],TAX_CALCULATION:["C100","C170","C175","C190","A100","A170","D100","F100","E110","M100","M500"],SPED_MASTER_DATA:["0150","0190","0200","0400"],SPED_DOCUMENT_TOTALS:["A100/A170","C100/C170/C175/C190","D100/D101/D105/D190","F100","E110","M100/M105/M200","M500/M505/M600"],SPED_ICMS_IPI_2026_TOTAL_EXCEPTION:["C100","C190"],RTC_2026_RATES:["NF-e/NFC-e","CBS","IBS","cClassTrib"]};
const category=(value:string):ValidationRule["category"]=>value==="RTC"?"REFORM":value.startsWith("SPED")?"SPED":value==="CLASSIFICATION"?"CADASTRAL":value==="OPERATION"||value==="ARITHMETIC"?"DOCUMENT":"FISCAL";
const severity=(code:string):ValidationRule["severity"]=>code.includes("FORMAT")||code.includes("CONTEXT")||code.includes("DIRECTION")?"HIGH":code.includes("EXCEPTION")?"LOW":"MEDIUM";
function official(rule:OfficialRule,changeLog:RuleChange[]):ValidationRule{return {id:`official:${rule.code}`,name:rule.name,category:category(rule.category),description:rule.description,validation:rule.description,alertCondition:rule.code.includes("EXCEPTION")?"Esta regra impede um falso alerta a partir da vigência indicada.":"Gera alerta quando o valor recebido diverge da regra oficial ou da consistência esperada.",expectedResult:rule.adjustableByAnalyst?"Conformidade com a referência oficial ou ajuste local vigente e justificado.":"Conformidade obrigatória com a estrutura oficial.",appliesTo:appliesTo[rule.code]??[],severity:severity(rule.code),active:true,adjustableByAnalyst:rule.adjustableByAnalyst,effectiveFrom:rule.effectiveFrom,effectiveTo:rule.effectiveTo,sources:rule.sources,origin:"OFFICIAL",version:rule.version,updatedAt:rule.updatedAt,changeLog:changeLog.filter(change=>change.ruleCodes.includes(rule.code))};}
export const validationRulesService={list:async()=>{const response=await api.get<ApiResponse<OfficialCatalog>>("/fiscal-validation/rules");const catalog=response.data.data;const officialRules=catalog.rules.map(rule=>official(rule,catalog.changeLog??[]));const adjustments=catalog.adjustments.map((row):ValidationRule=>({id:`client:${row.id}`,name:row.name,category:"FISCAL",description:row.reason,validation:`Ajuste local da regra ${row.ruleCode}. Critérios: ${JSON.stringify(row.criteria??{})}`,alertCondition:"Aplicado somente quando os critérios e a vigência do ajuste correspondem ao item analisado.",expectedResult:JSON.stringify(row.expected??{}),appliesTo:appliesTo[row.ruleCode]??[],severity:"MEDIUM",active:row.active!==false,adjustableByAnalyst:true,effectiveFrom:row.effectiveFrom,effectiveTo:row.effectiveTo,sources:row.evidenceUrl?[{authority:"Evidência informada pelo analista",title:"Fundamentação do ajuste local",url:row.evidenceUrl,retrievedAt:row.effectiveFrom}]:[],origin:"CLIENT",version:String(row.version??1),updatedAt:row.updatedAt}));const suggestions=(catalog.suggestions??[]).map((row):ValidationRule=>({id:`client:${row.id}`,name:row.name,category:"REFORM",description:row.description,validation:row.validation??"Aguardando definição manual após análise da alteração oficial.",alertCondition:"Não gera validação enquanto estiver inativa e pendente de revisão.",expectedResult:row.expectedResult??"Revisão fiscal, fundamentação e ativação manual pelo administrador.",appliesTo:["Reforma tributária","Fonte oficial monitorada"],severity:"MEDIUM",active:row.active,adjustableByAnalyst:true,sources:[{authority:"Fonte oficial monitorada",title:"Conteúdo que apresentou alteração",url:row.sourceUrl,retrievedAt:row.detectedAt}],origin:"CLIENT",version:String(row.version),updatedAt:row.detectedAt}));return [...officialRules,...adjustments,...suggestions];}};
