"use client";
import { AlertCircle, CheckCircle2, ChevronRight, CircleAlert, Clock3, Search, X } from "lucide-react";
import { cn } from "@/utils/cn";
import type { AlertStatus, ExecutionStatus, Severity } from "@/types";
export const cnx = cn;
export function Button({ children, className, variant="primary", ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "primary"|"secondary"|"ghost"|"danger" }) { const styles={primary:"bg-[#075d70] text-white hover:bg-[#064e5e]",secondary:"border border-[#8ca0b2] bg-white text-slate-700 hover:bg-slate-50",ghost:"text-[#176a84] hover:bg-cyan-50",danger:"bg-red-700 text-white hover:bg-red-800"}; return <button className={cn("inline-flex h-8 items-center justify-center gap-2 rounded-md px-3 text-sm font-semibold transition disabled:cursor-not-allowed disabled:opacity-50",styles[variant],className)} {...props}>{children}</button> }
export function Card({ children, className }: { children: React.ReactNode; className?: string }) { return <section className={cn("rounded-xl border border-[#aab8cb] bg-white shadow-[0_1px_2px_rgba(15,23,42,.04)]",className)}>{children}</section> }
const status: Record<string,[string,string]> = {OPEN:["Aberto","bg-red-100 text-red-800 ring-red-200"],IN_ANALYSIS:["Em análise","bg-amber-100 text-amber-800 ring-amber-200"],RESOLVED:["Resolvido","bg-emerald-100 text-emerald-800 ring-emerald-200"],IGNORED:["Ignorado","bg-slate-100 text-slate-700 ring-slate-200"],REOPENED:["Reaberto","bg-violet-100 text-violet-800 ring-violet-200"],PENDING:["Pendente","bg-[#d6e5ed] text-[#466b80] ring-[#b3cad7]"],RUNNING:["Em execução","bg-blue-100 text-blue-800 ring-blue-200"],COMPLETED:["Concluída","bg-emerald-100 text-emerald-800 ring-emerald-200"],FAILED:["Falhou","bg-red-100 text-red-800 ring-red-200"],CANCELED:["Cancelada","bg-slate-100 text-slate-700 ring-slate-200"]};
export function StatusBadge({ value }: { value: AlertStatus | ExecutionStatus | string }) { const [label, style] = status[value] ?? [value,"bg-slate-100 text-slate-700 ring-slate-200"]; return <span className={cn("inline-flex items-center rounded-full px-2 py-0.5 text-xs font-semibold ring-1",style)}>{label}</span> }
export function SeverityBadge({ value }: { value: Severity }) { const d={CRITICAL:["Crítica","bg-red-700 text-white"],HIGH:["Alta","bg-orange-100 text-orange-800"],MEDIUM:["Média","bg-amber-100 text-amber-800"],LOW:["Baixa","bg-blue-100 text-blue-800"]}[value]; return <span className={cn("rounded-full px-2 py-0.5 text-xs font-semibold",d[1])}>{d[0]}</span> }
export const money = (value:number) => new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(value);
export const dateTime = (value:string) => new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short",timeZone:"America/Sao_Paulo"}).format(new Date(value));
export function EmptyState({ title="Nenhum registro encontrado", description="Tente ajustar os filtros ou crie um novo registro." }: {title?:string;description?:string}) { return <div className="p-12 text-center"><div className="mx-auto mb-3 grid size-10 place-items-center rounded-full bg-slate-100"><Search size={18}/></div><p className="font-semibold text-slate-800">{title}</p><p className="mt-1 text-sm text-slate-500">{description}</p></div> }
export function ErrorState({ message="Não foi possível carregar estas informações." }: {message?:string}) { return <div className="flex items-center gap-3 rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-800"><AlertCircle size={18}/>{message}</div> }
export function PageHeader({ title, description, action }: {title:string;description?:string;action?:React.ReactNode}) { return <div className="mb-8 flex items-start justify-between gap-4"><div><div className="mb-4 flex items-center gap-1 text-xs text-slate-500">Início <ChevronRight size={13}/> {title}</div><h1 className="text-[32px] font-normal leading-none tracking-tight text-[#283456]">{title}</h1>{description && <p className="mt-2 text-lg text-slate-800">{description}</p>}</div>{action}</div> }
export function FilterBar({ children }: {children:React.ReactNode}) { return <div className="mb-5 flex flex-wrap items-center gap-2 rounded-md bg-white p-2">{children}<Button variant="ghost" className="ml-auto"><X size={15}/> Limpar filtros</Button></div> }
export function Notice({ children }: {children:React.ReactNode}) { return <div className="flex gap-2 rounded-lg border border-blue-200 bg-blue-50 p-3 text-sm text-blue-800"><CircleAlert size={17} className="shrink-0"/>{children}</div> }
export { CheckCircle2, Clock3 };
