"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { CheckCircle2, CirclePlay, Eye, MoreHorizontal, Plus, Search, SlidersHorizontal } from "lucide-react";
import { alerts, executions, listMockConnections } from "@/services/mocks/data";
import { Button, Card, ErrorState, FilterBar, PageHeader, SeverityBadge, StatusBadge, dateTime, money } from "@/components/shared/ui";
import { connectionsService } from "@/services/connections.service";

const info:Record<string,{title:string;desc:string;create:string}>={connections:{title:"Conexões ERP",desc:"Gerencie os Connectors autorizados para acesso ao ERP.",create:"Nova conexão"},"data-sources":{title:"Fontes de dados",desc:"Configure as fontes e o mapeamento semântico do ERP.",create:"Nova fonte"},rules:{title:"Regras de conciliação",desc:"Defina como os títulos financeiros são comparados aos lançamentos contábeis.",create:"Nova regra"},executions:{title:"Execuções",desc:"Acompanhe os processamentos manuais realizados.",create:""},alerts:{title:"Central de alertas",desc:"Analise e trate as divergências encontradas nas conciliações.",create:""}};
export default function ListPage(){const {section}=useParams<{section:string}>(), config=info[section]; const [query,setQuery]=useState("");if(!config)return null;return <><PageHeader title={config.title} description={config.desc} action={config.create?<Link href={`/${section}/new`}><Button><Plus size={16}/>{config.create}</Button></Link>:undefined}/><FilterBar><div className="flex h-9 min-w-56 items-center gap-2 rounded-lg border border-slate-200 px-3"><Search size={16} className="text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} className="w-full outline-none text-sm" placeholder="Buscar..."/></div><Button variant="secondary"><SlidersHorizontal size={15}/> Filtros</Button></FilterBar>{section==="alerts"?<Alerts query={query}/>:section==="executions"?<Executions/>:section==="connections"?<Connections/>:section==="rules"?<Rules/>:<Sources/>}</>}
function Table({children}:{children:React.ReactNode}){return <Card className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-left text-sm">{children}</table></div></Card>}; const Head=({children}:{children?:React.ReactNode})=><th className="whitespace-nowrap bg-slate-50 px-4 py-3 text-xs font-semibold uppercase tracking-wide text-slate-500">{children}</th>;const Cell=({children}:{children:React.ReactNode})=><td className="whitespace-nowrap border-t border-slate-100 px-4 py-3 text-slate-600">{children}</td>;
function Alerts({query}:{query:string}){const rows=alerts.filter(a=>JSON.stringify(a).toLowerCase().includes(query.toLowerCase()));return <Table><thead><tr><Head>Severidade</Head><Head>Empresa</Head><Head>Documento</Head><Head>Pessoa</Head><Head>Regra</Head><Head>Diferença</Head><Head>Status</Head><Head>Criado em</Head><Head/></tr></thead><tbody>{rows.map(a=><tr key={a.id}><Cell><SeverityBadge value={a.severity}/></Cell><Cell>{a.company}<small className="block text-xs text-slate-400">{a.branch}</small></Cell><Cell><b className="text-slate-800">{a.document}</b></Cell><Cell>{a.person}</Cell><Cell>{a.rule}</Cell><Cell><b className="text-red-700">{money(a.difference)}</b></Cell><Cell><StatusBadge value={a.status}/></Cell><Cell>{dateTime(a.createdAt)}</Cell><Cell><Link href={`/alerts/${a.id}`}><Button variant="ghost" title="Ver alerta"><Eye size={16}/></Button></Link></Cell></tr>)}</tbody></Table>}
function Executions(){return <Table><thead><tr><Head>Regra</Head><Head>Início</Head><Head>Duração</Head><Head>Analisados</Head><Head>Conciliados</Head><Head>Divergentes</Head><Head>Valor divergente</Head><Head>Status</Head><Head/></tr></thead><tbody>{executions.map(e=><tr key={e.id}><Cell><b className="text-slate-800">{e.rule}</b><small className="block text-xs text-slate-400">{e.id}</small></Cell><Cell>{dateTime(e.startedAt)}</Cell><Cell>{e.endedAt?"4 min 32 s":"Em andamento"}</Cell><Cell>{e.analyzed.toLocaleString("pt-BR")}</Cell><Cell>{e.matched.toLocaleString("pt-BR")}</Cell><Cell>{e.divergent.toLocaleString("pt-BR")}</Cell><Cell>{money(e.amount)}</Cell><Cell><StatusBadge value={e.status}/></Cell><Cell><Link href={`/executions/${e.id}`}><Button variant="ghost"><Eye size={16}/></Button></Link></Cell></tr>)}</tbody></Table>}
function Connections(){const mockMode=process.env.NEXT_PUBLIC_USE_MOCKS==="true";const query=useQuery({queryKey:["connections"],queryFn:connectionsService.list,enabled:!mockMode});if(query.isLoading&&!mockMode)return <Card className="p-8 text-sm text-slate-500">Carregando conexões...</Card>;if(query.isError&&!mockMode)return <ErrorState message="Não foi possível carregar os Connectors. Verifique se a API está disponível."/>;const rows=mockMode?listMockConnections():query.data?.items??[];return <Table><thead><tr><Head>Nome</Head><Head>URL do Connector</Head><Head>ID</Head><Head>Status</Head><Head>Versão</Head><Head>API Key</Head><Head>Último heartbeat</Head><Head/></tr></thead><tbody>{rows.map(c=><tr key={c.id}><Cell><b className="text-slate-800">{c.name}</b></Cell><Cell>{c.connectorBaseUrl}</Cell><Cell><code className="text-xs">{c.connectorId}</code></Cell><Cell><StatusBadge value={c.connectorStatus}/></Cell><Cell>{c.connectorVersion??"—"}</Cell><Cell>{c.apiKeyConfigured?"Configurada":"Não configurada"}</Cell><Cell>{c.lastHeartbeatAt?dateTime(c.lastHeartbeatAt):"Ainda não verificado"}</Cell><Cell><Link href={`/connections/${c.id}/edit`}><Button variant="ghost"><MoreHorizontal size={17}/></Button></Link></Cell></tr>)}</tbody></Table>}
function Rules(){const r=["Títulos sem contabilização","Diferença de valores"];return <Table><thead><tr><Head>Nome</Head><Head>Tipo</Head><Head>Origem</Head><Head>Destino</Head><Head>Severidade</Head><Head>Tolerância</Head><Head>Status</Head><Head>Última execução</Head><Head/></tr></thead><tbody>{r.map((n,i)=><tr key={n}><Cell><b className="text-slate-800">{n}</b><small className="block text-xs text-slate-400">Regra de produção</small></Cell><Cell>{i?"Comparação de valores":"Verificação de existência"}</Cell><Cell>Títulos a pagar</Cell><Cell>Lançamentos contábeis</Cell><Cell><SeverityBadge value={i?"HIGH":"CRITICAL"}/></Cell><Cell>{i?money(50):"—"}</Cell><Cell><StatusBadge value="RESOLVED"/></Cell><Cell>24/07/2026 08:00</Cell><Cell><Link href={`/rules/rule-${i+1}`}><Button variant="ghost"><MoreHorizontal size={17}/></Button></Link></Cell></tr>)}</tbody></Table>}
function Sources(){const rows=[["Títulos a pagar","ACCOUNTS_PAYABLE","Oracle Produção","APPS.AP_INVOICES_ALL","14"],["Lançamentos contábeis","ACCOUNTING_ENTRY","Oracle Produção","APPS.GL_JE_LINES","18"]];return <Table><thead><tr><Head>Nome</Head><Head>Tipo</Head><Head>Conexão</Head><Head>Tabela</Head><Head>Campos</Head><Head>Status</Head><Head/></tr></thead><tbody>{rows.map(r=><tr key={r[0]}><Cell><b className="text-slate-800">{r[0]}</b></Cell><Cell>{r[1]==="ACCOUNTS_PAYABLE"?"Títulos a pagar":"Lançamentos contábeis"}</Cell><Cell>{r[2]}</Cell><Cell><code className="text-xs">{r[3]}</code></Cell><Cell>{r[4]}</Cell><Cell><StatusBadge value="RESOLVED"/></Cell><Cell><Button variant="ghost"><MoreHorizontal size={17}/></Button></Cell></tr>)}</tbody></Table>}
