"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useQuery } from "@tanstack/react-query";
import { MoreHorizontal, Plus } from "lucide-react";
import { Button, Card, ErrorState, PageHeader, StatusBadge, dateTime } from "@/components/shared/ui";
import { connectionsService } from "@/services/connections.service";

export default function SectionPage(){const {section}=useParams<{section:string}>();if(section!=="connections")return null;return <><PageHeader title="Conexões ERP" description="Gerencie os Connectors autorizados para acesso ao ERP." action={<Link href="/connections/new"><Button><Plus size={16}/>Nova conexão</Button></Link>}/><Connections/></>}
function Connections(){const query=useQuery({queryKey:["connections"],queryFn:connectionsService.list});if(query.isLoading)return <Card className="p-8 text-sm text-slate-500">Carregando conexões...</Card>;if(query.isError)return <ErrorState message="Não foi possível carregar os Connectors. Verifique a conexão com a API."/>;const rows=query.data?.items??[];return <Card className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{["Nome","URL do Connector","ID","Status","Versão","API Key","Último heartbeat",""] .map(label=><th key={label} className="whitespace-nowrap bg-slate-50 px-4 py-3 text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</th>)}</tr></thead><tbody>{rows.map(connection=><tr key={connection.id}><Cell><b className="text-slate-800">{connection.name}</b></Cell><Cell>{connection.connectorBaseUrl}</Cell><Cell><code className="text-xs">{connection.connectorId}</code></Cell><Cell><StatusBadge value={connection.connectorStatus}/></Cell><Cell>{connection.connectorVersion??"—"}</Cell><Cell>{connection.apiKeyConfigured?"Configurada":"Não configurada"}</Cell><Cell>{connection.lastHeartbeatAt?dateTime(connection.lastHeartbeatAt):"Ainda não verificado"}</Cell><Cell><Link href={`/connections/${connection.id}/edit`}><Button variant="ghost"><MoreHorizontal size={17}/></Button></Link></Cell></tr>)}</tbody></table>{!rows.length&&<p className="p-8 text-center text-sm text-slate-500">Nenhum Connector cadastrado.</p>}</div></Card>}
function Cell({children}:{children:React.ReactNode}){return <td className="whitespace-nowrap border-t border-slate-100 px-4 py-3 text-slate-600">{children}</td>}
