"use client";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { Bell, ChevronDown, Database, Gauge, ListChecks, LogOut, PlayCircle, ShieldCheck } from "lucide-react";
import { useEffect } from "react";
import { useAuth } from "@/providers/providers";
import { cn } from "@/utils/cn";
const navigation=[{href:"/dashboard",label:"Dashboard",icon:Gauge},{href:"/alerts",label:"Alertas",icon:Bell},{href:"/executions",label:"Execuções",icon:PlayCircle},{href:"/rules",label:"Regras",icon:ListChecks,admin:true},{href:"/data-sources",label:"Fontes de dados",icon:Database,admin:true},{href:"/connections",label:"Conexões ERP",icon:ShieldCheck,admin:true}];
export function AppShell({ children }: {children:React.ReactNode}) { const path=usePathname(), router=useRouter(), {user,logout}=useAuth(); useEffect(()=>{ if(!user) router.replace("/login"); else if(user.mustChangePassword) router.replace("/change-password"); else if(user.role==="ANALYST" && ["/rules","/data-sources","/connections"].some(x=>path.startsWith(x))) router.replace("/dashboard"); },[user,path,router]); if(!user) return null; return <div className="min-h-screen bg-slate-50"><aside className="fixed inset-y-0 left-0 z-20 hidden w-64 border-r border-slate-800 bg-slate-950 text-slate-300 lg:flex lg:flex-col"><Link href="/dashboard" className="flex h-18 items-center gap-3 border-b border-slate-800 px-6 py-5"><span className="grid size-8 place-items-center rounded-lg bg-blue-600 font-bold text-white">C</span><span><b className="block text-sm text-white">Concilia ERP</b><small className="text-xs text-slate-500">Auditoria e controle</small></span></Link><nav className="flex-1 space-y-1 p-3">{navigation.filter(i=>!i.admin||user.role==="ADMIN").map(item=>{const Icon=item.icon, active=path===item.href||path.startsWith(item.href+"/");return <Link key={item.href} href={item.href} className={cn("flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium transition",active?"bg-blue-600 text-white":"hover:bg-slate-800 hover:text-white")}><Icon size={18}/>{item.label}</Link>})}</nav><div className="m-3 rounded-lg border border-slate-800 bg-slate-900 p-3 text-xs text-slate-400"><b className="mb-1 block text-slate-200">Ambiente de desenvolvimento</b>Dados simulados ativos</div></aside><main className="lg:pl-64"><header className="sticky top-0 z-10 flex h-18 items-center justify-between border-b border-slate-200 bg-white/95 px-5 backdrop-blur lg:px-8"><div><p className="text-sm font-semibold text-slate-800">{navigation.find(i=>path.startsWith(i.href))?.label ?? "Concilia ERP"}</p><p className="text-xs text-slate-500">Controle de conciliações</p></div><div className="flex items-center gap-3"><button className="relative rounded-lg p-2 text-slate-500 hover:bg-slate-100"><Bell size={19}/><i className="absolute right-2 top-2 size-1.5 rounded-full bg-red-500"/></button><div className="h-7 w-px bg-slate-200"/><div className="text-right"><p className="text-sm font-semibold text-slate-800">{user.name}</p><p className="text-xs text-slate-500">{user.role === "ADMIN" ? "Administrador" : "Analista"}</p></div><button onClick={()=>{logout();router.replace("/login")}} title="Sair" className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><LogOut size={18}/></button></div></header><div className="p-5 lg:p-8">{children}</div></main></div> }
