"use client";
import Link from "next/link";
import { useMemo, useRef, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { ArrowRight, Building2, Check, CheckCircle2, Download, Edit3, FileSpreadsheet, FileWarning, Info, Layers3, LoaderCircle, PackageSearch, Search, Send, ShieldAlert, Upload, X } from "lucide-react";
import { Button, Card, ErrorState, PageHeader } from "@/components/shared/ui";
import { getApiErrorMessage } from "@/services/api/client";
import { fiscalAlertsService, type FiscalAlertEntity, type FiscalAlertGroup, type FiscalAlertItem, type FiscalAlertSeverity, type FiscalSuggestionReference } from "@/services/fiscal-alerts.service";

const entityLabel:Record<FiscalAlertEntity,string>={PRODUCT:"Produtos",TAXATION:"Tributações",FAMILY:"Famílias",SUPPLIER:"Fornecedores",SPED:"SPED"};
const severityLabel:Record<FiscalAlertSeverity,string>={CRITICAL:"Crítica",HIGH:"Alta",MEDIUM:"Média",LOW:"Baixa"};
const severityStyle:Record<FiscalAlertSeverity,string>={CRITICAL:"border-red-300 bg-red-50 text-red-800",HIGH:"border-orange-300 bg-orange-50 text-orange-800",MEDIUM:"border-amber-300 bg-amber-50 text-amber-800",LOW:"border-blue-300 bg-blue-50 text-blue-800"};

export default function FiscalAlertsPage(){
  const alerts=useQuery({queryKey:["fiscal-alerts","summary"],queryFn:fiscalAlertsService.summary});
  const validation=useMutation({mutationFn:fiscalAlertsService.scanCatalog,onSuccess:async()=>{await alerts.refetch();}});
  const [selectedId,setSelectedId]=useState<string>();
  const [entity,setEntity]=useState<FiscalAlertEntity|"ALL">("ALL");
  const [search,setSearch]=useState("");
  const visible=useMemo(()=>(alerts.data??[]).filter(group=>entity==="ALL"||group.entity===entity),[alerts.data,entity]);
  const selected=(alerts.data??[]).find(group=>group.id===selectedId)??visible[0];
  if(alerts.isError)return <><PageHeader title="Central de Alertas" description="Pendências cadastrais e fiscais do cliente."/><ErrorState/></>;
  return <>
    <PageHeader title="Central de Alertas" description="Pendências identificadas nos produtos, tributações e cadastros do cliente." action={<Button onClick={()=>validation.mutate()} disabled={validation.isPending}>{validation.isPending?<LoaderCircle size={16} className="animate-spin"/>:<ShieldAlert size={16}/>} {validation.isPending?"Validando...":"Gerar alertas fiscais"}</Button>}/>
    {validation.isSuccess&&<div role="status" className="mb-5 flex items-center gap-2 rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm font-medium text-emerald-800"><CheckCircle2 size={17}/>Validação concluída. Os alertas persistidos foram atualizados.</div>}
    {validation.isError&&<div role="alert" className="mb-5"><ErrorState message={getApiErrorMessage(validation.error)}/></div>}
    <FiscalBatchActions/>
    <div className="mb-5 flex max-w-5xl flex-wrap gap-2">{(["ALL","PRODUCT","TAXATION","SPED","FAMILY","SUPPLIER"] as const).map(value=><Button key={value} variant={entity===value?"primary":"secondary"} onClick={()=>{setEntity(value);setSelectedId(undefined);}}>{value==="ALL"?"Todas":entityLabel[value]}</Button>)}</div>
    {alerts.isLoading?<LoadingCards/>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{visible.map(group=><AlertCard key={group.id} group={group} selected={selected?.id===group.id} select={()=>setSelectedId(group.id)}/>)}</div>}
    {selected&&<Card className="mt-6 overflow-visible">
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 p-5"><div><p className="text-xs font-semibold uppercase tracking-wide text-cyan-700">{entityLabel[selected.entity]} · {selected.field}</p><h2 className="mt-1 text-lg font-bold text-slate-900">{selected.title}</h2><p className="mt-1 text-sm text-slate-500">Comparação da situação atual com a sugestão de correção.</p></div><label className="flex h-10 items-center gap-2 rounded-lg border border-slate-300 px-3"><Search size={16} className="text-slate-400"/><input value={search} onChange={event=>setSearch(event.target.value)} className="min-w-48 bg-transparent text-sm outline-none" placeholder="Pesquisar nesta pendência"/></label></div>
      <AlertItems group={selected} search={search}/>
    </Card>}
  </>;
}

function FiscalBatchActions(){const input=useRef<HTMLInputElement>(null);const [batch,setBatch]=useState<Awaited<ReturnType<typeof fiscalAlertsService.importCorrections>>>();const [message,setMessage]=useState("");const exportData=async(format:"xlsx"|"csv")=>{const rows=await fiscalAlertsService.correctionRows();if(!rows.length){setMessage("Nenhuma proposta fiscal disponível para exportação.");return;}const XLSX=await import("xlsx");const sheet=XLSX.utils.json_to_sheet(rows);if(format==="xlsx"){const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,sheet,"De-Para Fiscal");XLSX.writeFile(book,"de-para-fiscal.xlsx");}else{const csv=XLSX.utils.sheet_to_csv(sheet,{FS:";"});const url=URL.createObjectURL(new Blob(["\uFEFF"+csv],{type:"text/csv;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download="de-para-fiscal.csv";link.click();URL.revokeObjectURL(url);}setMessage(`${rows.length} produto(s) exportado(s).`);};const importFile=async(file?:File)=>{if(!file)return;const XLSX=await import("xlsx");const book=XLSX.read(await file.arrayBuffer(),{type:"array"});const sheet=book.Sheets[book.SheetNames[0]];const rows=XLSX.utils.sheet_to_json<Record<string,string|number|null>>(sheet,{defval:""});const result=await fiscalAlertsService.importCorrections(rows,file.name);setBatch(result);setMessage(result.validationRate===100?"Planilha 100% validada. A atualização do ERP foi liberada.":`${result.invalidRows} linha(s) possuem erros; corrija e importe novamente.`);};const queue=useMutation({mutationFn:()=>fiscalAlertsService.queueCorrectionBatch(batch!.id),onSuccess:data=>{setMessage(`${data.queued} atualização(ões) enviadas para a fila da API do ERP.`);setBatch(previous=>previous?{...previous,status:"QUEUED_FOR_ERP"}:previous);}});return <Card className="mb-5 flex max-w-6xl flex-wrap items-center gap-2 p-4"><span className="mr-auto flex items-center gap-2 text-sm font-semibold text-slate-700"><FileSpreadsheet size={18} className="text-cyan-700"/>De/Para fiscal dos produtos importados</span><Button variant="secondary" onClick={()=>void exportData("xlsx")}><Download size={16}/>Excel</Button><Button variant="secondary" onClick={()=>void exportData("csv")}><Download size={16}/>CSV ;</Button><input ref={input} type="file" accept=".xlsx,.xls,.csv" className="hidden" onChange={event=>void importFile(event.target.files?.[0])}/><Button variant="secondary" onClick={()=>input.current?.click()}><Upload size={16}/>Importar e validar</Button>{batch?.validationRate===100&&batch.status!=="QUEUED_FOR_ERP"&&<Button onClick={()=>queue.mutate()} disabled={queue.isPending}><Send size={16}/>Atualizar ERP via API</Button>}{message&&<p className={`w-full text-sm ${batch&&batch.validationRate<100?"text-red-700":"text-emerald-700"}`}>{message}</p>}{batch?.errors.slice(0,5).map(error=><p key={error.rowNumber} className="w-full text-xs text-red-700">Linha {error.rowNumber}: {error.errors.join("; ")}</p>)}</Card>}
function LoadingCards(){return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{[1,2,3].map(item=><div key={item} className="h-40 animate-pulse rounded-xl bg-slate-100"/>)}</div>}
function AlertCard({group,selected,select}:{group:FiscalAlertGroup;selected:boolean;select:()=>void}){return <button type="button" onClick={select} className="text-left"><Card className={`h-full p-5 transition hover:-translate-y-0.5 hover:border-cyan-400 hover:shadow-md ${selected?"border-cyan-600 ring-2 ring-cyan-100":""}`}><div className="flex items-start justify-between gap-3"><span className="grid size-10 place-items-center rounded-lg bg-cyan-50 text-cyan-700"><EntityIcon entity={group.entity}/></span><span className={`rounded-full border px-2 py-0.5 text-xs font-semibold ${severityStyle[group.severity]}`}>{severityLabel[group.severity]}</span></div><strong className="mt-4 block text-slate-900">{group.title}</strong><p className="mt-1 min-h-10 text-sm text-slate-500">{group.description}</p><div className="mt-4 flex items-end justify-between"><span><b className="block text-2xl text-slate-900">{group.affected}</b><small className="text-slate-500">registros afetados</small></span><span className="text-xs font-semibold text-cyan-700">Ver De/Para →</span></div></Card></button>}
function AlertItems({group,search}:{group:FiscalAlertGroup;search:string}){
  const term=search.trim().toLocaleLowerCase("pt-BR");
  const items=group.items.filter(item=>!term||`${item.code} ${item.description} ${item.currentValue} ${item.suggestedValue} ${item.source} ${Object.values(item.suggestionReference??{}).join(" ")}`.toLocaleLowerCase("pt-BR").includes(term));
  return <div>{items.map(item=>{
    const productId=item.productId??item.maintenanceId??item.id;
    const href=`/catalog-review?productId=${encodeURIComponent(productId)}&code=${encodeURIComponent(item.code)}&from=alerts`;
    return <div key={item.id} className="border-b border-slate-100 p-5 last:border-0">
      <div className="mb-4 flex flex-wrap items-start justify-between gap-3"><div><strong className="text-slate-900">{item.description}</strong><p className="font-mono text-xs text-slate-500">{item.code}</p></div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700">{item.confidence}% de confiança</span><Link href={href} className="inline-flex h-9 items-center gap-2 rounded-lg bg-cyan-700 px-3 text-sm font-semibold text-white hover:bg-cyan-800"><Edit3 size={15}/>Abrir manutenção</Link></div></div>
      <div className="grid items-stretch gap-3 md:grid-cols-[1fr_auto_1fr]"><Comparison label="De · situação atual" value={item.currentValue} tone="current"/><span className="grid place-items-center text-cyan-600"><ArrowRight size={20}/></span><SuggestionComparison item={item}/></div>
      {item.spedContext&&<div className="mt-3 rounded-lg border border-blue-200 bg-blue-50 p-3 text-sm text-blue-950"><b>{item.spedContext.bookkeeping==="EFD_CONTRIBUTIONS"?"EFD-Contribuições":"EFD ICMS/IPI"}</b><span className="ml-2">Registro {item.spedContext.record||"não identificado"}{item.spedContext.parentRecord?` · pai ${item.spedContext.parentRecord}`:""}{item.spedContext.line?` · linha ${item.spedContext.line}`:""}</span><p className="mt-1 text-xs">Registros relacionados: {item.spedContext.relatedRecords.join(", ")||"consultar registro de origem"}</p>{item.spedContext.sourceFile&&<p className="mt-1 font-mono text-xs">{item.spedContext.sourceFile}</p>}</div>}
      {item.actionable===false?<p className="mt-3 text-xs text-slate-500">A correção deve ser realizada na origem da escrituração e o arquivo SPED deve ser validado novamente.</p>:<AdjustmentActions group={group} item={item}/>}
    </div>;
  })}{!items.length&&<p className="p-8 text-center text-sm text-slate-500">Nenhum registro corresponde à pesquisa.</p>}</div>;
}
function Comparison({label,value,tone}:{label:string;value:string;tone:"current"|"suggested"}){return <div className={`rounded-lg border p-4 ${tone==="current"?"border-red-200 bg-red-50":"border-emerald-200 bg-emerald-50"}`}><p className={`text-xs font-semibold uppercase tracking-wide ${tone==="current"?"text-red-700":"text-emerald-700"}`}>{label}</p><strong className="mt-1 block text-slate-900">{value}</strong></div>}
function SuggestionComparison({item}:{item:FiscalAlertItem}){
  return <div tabIndex={0} aria-describedby={`suggestion-${item.id}`} className="group relative rounded-lg border border-emerald-200 bg-emerald-50 p-4 outline-none focus-visible:ring-2 focus-visible:ring-emerald-600">
    <p className="flex items-center gap-1.5 text-xs font-semibold uppercase tracking-wide text-emerald-700">Para · sugestão <Info size={14} aria-hidden="true"/></p><strong className="mt-1 block text-slate-900">{item.suggestedValue}</strong><span className="mt-2 block text-[11px] text-emerald-800">Passe o mouse para entender a sugestão</span>
    <SuggestionDetails id={`suggestion-${item.id}`} source={item.source} reference={item.suggestionReference}/>
  </div>;
}
function SuggestionDetails({id,source,reference}:{id:string;source:string;reference?:FiscalSuggestionReference}){
  const rows=[["Tabela de referência",reference?.table],["Origem",reference?.origin??source],["Estado do cliente",reference?.clientState],["Regra aplicada",reference?.rule],["Motivo",reference?.reason]];
  return <div id={id} role="tooltip" className="pointer-events-none invisible absolute bottom-[calc(100%+8px)] left-0 z-20 w-full min-w-72 translate-y-1 rounded-lg bg-slate-900 p-4 text-left normal-case text-white opacity-0 shadow-xl transition group-hover:visible group-hover:translate-y-0 group-hover:opacity-100 group-focus:visible group-focus:translate-y-0 group-focus:opacity-100"><p className="mb-2 text-xs font-bold uppercase tracking-wide text-cyan-300">Referência da sugestão</p><dl className="grid gap-2">{rows.map(([label,value])=><div key={label}><dt className="text-[11px] text-slate-400">{label}</dt><dd className="text-xs font-medium">{value||"Não informado pela regra"}</dd></div>)}</dl><span className="absolute -bottom-1 left-6 size-2 rotate-45 bg-slate-900"/></div>;
}
function AdjustmentActions({group,item}:{group:FiscalAlertGroup;item:FiscalAlertItem}){
  const [mode,setMode]=useState<"ACCEPTED"|"EDITED"|null>(null);
  const [value,setValue]=useState(item.suggestedValue);
  const queue=useMutation({mutationFn:()=>fiscalAlertsService.queueAdjustment({groupId:group.id,itemId:item.id,field:group.field,value:value.trim(),decision:mode!}),onSuccess:()=>setMode(null)});
  if(queue.isSuccess)return <div role="status" className="mt-4 flex items-center gap-2 rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm font-medium text-emerald-800"><CheckCircle2 size={17}/>Ajuste enviado para a fila de integração.</div>;
  return <div className="mt-4 rounded-lg border border-slate-200 bg-slate-50 p-3">
    {!mode?<div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-slate-600">Qual decisão deve seguir para a integração?</p><div className="flex flex-wrap gap-2"><Button onClick={()=>{setValue(item.suggestedValue);setMode("ACCEPTED");}}><Check size={16}/>Acatar sugestão</Button><Button variant="secondary" onClick={()=>setMode("EDITED")}><Edit3 size={16}/>Editar informação</Button></div></div>:<div className="grid gap-3"><label className="grid gap-1 text-sm font-semibold text-slate-700">Valor que será integrado<input autoFocus={mode==="EDITED"} value={value} onChange={event=>{setValue(event.target.value);setMode("EDITED");}} readOnly={mode==="ACCEPTED"} className={`h-10 rounded-lg border border-slate-300 px-3 font-normal outline-none focus:border-cyan-600 ${mode==="ACCEPTED"?"bg-emerald-50":"bg-white"}`}/></label><div className="flex flex-wrap items-center justify-between gap-2"><span className="text-xs text-slate-500">{mode==="ACCEPTED"?"Sugestão acatada sem alterações.":"Valor ajustado manualmente pelo analista."}</span><div className="flex gap-2"><Button variant="ghost" onClick={()=>{setMode(null);setValue(item.suggestedValue);}} disabled={queue.isPending}><X size={15}/>Cancelar</Button><Button onClick={()=>queue.mutate()} disabled={queue.isPending||!value.trim()}><Send size={15}/>{queue.isPending?"Enviando...":"Enviar para integração"}</Button></div></div></div>}
    {queue.isError&&<p role="alert" className="mt-3 text-sm text-red-700">{getApiErrorMessage(queue.error)}</p>}
  </div>;
}
function EntityIcon({entity}:{entity:FiscalAlertEntity}){if(entity==="PRODUCT")return <PackageSearch size={20}/>;if(entity==="TAXATION")return <ShieldAlert size={20}/>;if(entity==="SPED")return <FileWarning size={20}/>;if(entity==="FAMILY")return <Layers3 size={20}/>;return <Building2 size={20}/>}
