"use client";

import Link from "next/link";
import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { Eye } from "lucide-react";
import { Card, ErrorState, PageHeader } from "@/components/shared/ui";
import { connectorTransmissionsService, type TransmissionPage, type TransmissionSummary, type ValidatedProduct } from "@/services/connector-transmissions.service";

const issueLabels: Record<string, string> = { all: "Todos os itens", ok: "Itens sem pendência", ncm: "Itens com NCM pendente", cest: "Itens com CEST pendente", cst: "Itens com CST ICMS pendente", cfop: "Itens com CFOP pendente" };

export default function ConnectorDataPage() {
  const [fileFilter, setFileFilter] = useState("");
  const [transmissionPage, setTransmissionPage] = useState(1);
  const [issue, setIssue] = useState("");
  const transmissions = useQuery({ queryKey: ["connector-transmissions", transmissionPage, fileFilter], queryFn: () => connectorTransmissionsService.list({ page: transmissionPage, file: fileFilter }) });
  const summary = useQuery({ queryKey: ["connector-transmission-summary"], queryFn: connectorTransmissionsService.summary });
  const validationProducts = useQuery({ queryKey: ["connector-validation-products", issue], queryFn: () => connectorTransmissionsService.products(issue), enabled: Boolean(issue) });
  const proposals = useQuery({ queryKey: ["sped-fiscal-proposals"], queryFn: connectorTransmissionsService.spedProposals });

  return <>
    <PageHeader title="Cadastro fiscal importado" description="Selecione um status para consultar os produtos recebidos e suas pendências de cadastro." />
    {summary.isError ? <ErrorState message="Não foi possível carregar o resumo dos produtos importados." /> : <TransmissionSummaryCards summary={summary.data} loading={summary.isLoading} selectedIssue={issue} select={setIssue} />}
    {proposals.data?.items.length ? <SpedProposals items={proposals.data.items} total={proposals.data.total} /> : null}
    <ValidationProducts issue={issue} loading={validationProducts.isLoading} error={validationProducts.isError} items={validationProducts.data} />
    {transmissions.isError ? <ErrorState message="Não foi possível carregar os lotes enviados pelo Connector." /> : <TransmissionList data={transmissions.data} loading={transmissions.isLoading} file={fileFilter} setFile={(value) => { setFileFilter(value); setTransmissionPage(1); }} setPage={setTransmissionPage} />}
  </>;
}

function SpedProposals({ items, total }: { items: Awaited<ReturnType<typeof connectorTransmissionsService.spedProposals>>["items"]; total: number }) { return <Card className="mb-5 overflow-hidden"><div className="border-b p-4"><b className="text-slate-800">Propostas fiscais geradas do SPED</b><span className="ml-2 text-sm text-slate-500">{total} pendente(s) de revisão</span></div><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-sm"><thead><tr className="bg-slate-50 text-xs uppercase text-slate-500"><th className="p-3 text-left">Produto / família sugerida</th><th className="p-3 text-left">NCM / CEST</th><th className="p-3 text-left">CST / CFOP observados</th><th className="p-3 text-left">Alíquota efetiva</th><th className="p-3 text-left">Regras</th></tr></thead><tbody>{items.map(item => <tr key={item.id} className="border-t border-slate-100"><td className="p-3"><b className="block">{item.canonicalDescription}</b><small className="text-slate-500">{item.productCode} · {item.familyName || item.familyKey || "Família a definir"}</small></td><td className="p-3">{item.ncm || "—"} / {item.cest || "—"}</td><td className="p-3">{item.taxation.cstIcms || "—"} / {item.taxation.cfop || "—"}</td><td className="p-3">ICMS {item.evidence.effectiveIcmsRate ?? "—"}% · IPI {item.evidence.effectiveIpiRate ?? "—"}%</td><td className="p-3">{item.validation.error ? "Validação indisponível" : `${item.validation.matchedRules?.length ?? 0} regra(s) encontrada(s)`}</td></tr>)}</tbody></table></div></Card>; }

function TransmissionSummaryCards({ summary, loading, selectedIssue, select }: { summary?: TransmissionSummary; loading: boolean; selectedIssue: string; select: (issue: string) => void }) {
  const cards = [["Total de itens", summary?.totalItems ?? summary?.products ?? 0, "all"], ["Sem pendência", summary?.withoutPending ?? 0, "ok"], ["NCM pendente", summary?.missingNcm ?? 0, "ncm"], ["CEST pendente", summary?.missingCest ?? 0, "cest"], ["CST ICMS pendente", summary?.missingCstIcms ?? 0, "cst"], ["CFOP pendente", summary?.missingCfop ?? 0, "cfop"]];
  return <section className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-6" aria-label="Resumo de produtos importados">{cards.map(([label, total, issue]) => <button key={String(issue)} type="button" onClick={() => select(String(issue))} aria-pressed={selectedIssue === issue} className="rounded-lg text-left focus:outline-none focus:ring-2 focus:ring-blue-500"><Card className={`h-full p-4 transition hover:border-blue-300 hover:shadow-sm ${selectedIssue === issue ? "border-blue-500 bg-blue-50" : ""}`}><p className="text-xs font-semibold uppercase text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold text-slate-900">{loading ? "—" : total}</p><p className="mt-2 text-xs text-blue-700">Ver produtos</p></Card></button>)}</section>;
}

function ValidationProducts({ issue, loading, error, items }: { issue: string; loading: boolean; error: boolean; items?: ValidatedProduct[] }) {
  if (!issue) return null;
  if (error) return <ErrorState message="Não foi possível carregar os produtos deste status." />;
  return <Card className="mb-5 overflow-x-auto"><div className="border-b p-4"><b className="text-slate-800">{issueLabels[issue] ?? "Produtos importados"}</b><span className="ml-2 text-sm text-slate-500">{loading ? "Carregando..." : `${items?.length ?? 0} item(ns)`}</span></div>{loading ? <p className="p-5 text-sm text-slate-500">Carregando produtos...</p> : <><table className="w-full min-w-[720px] text-sm"><thead><tr className="border-b bg-slate-50 text-xs uppercase text-slate-500"><th className="p-3 text-left">Produto</th><th className="p-3 text-left">NCM / CEST</th><th className="p-3 text-left">CST / CFOP</th><th className="p-3 text-left">Arquivos SPED de origem</th><th className="p-3 text-right"><span className="sr-only">Ações</span></th></tr></thead><tbody>{items?.map(item => <tr key={item.code} className="border-t border-slate-100"><td className="p-3"><b className="block text-slate-800">{item.description}</b><small className="font-mono text-slate-500">{item.code}</small></td><td className="p-3">{item.ncm || "—"} / {item.cest || "—"}</td><td className="p-3">{item.cstIcms || "—"} / {item.cfop || "—"}</td><td className="p-3">{item.files.join(", ") || "—"}</td><td className="p-3 text-right"><Link href={`/connector-data/products/${encodeURIComponent(item.code)}`} className="inline-flex items-center gap-1.5 rounded-md bg-blue-700 px-3 py-1.5 text-xs font-semibold text-white transition hover:bg-blue-800 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"><Eye size={14} />Detalhes</Link></td></tr>)}</tbody></table>{!items?.length && <p className="p-8 text-center text-sm text-slate-500">Nenhum produto encontrado para este status.</p>}</>}</Card>;
}

function TransmissionList({ data, loading, file, setFile, setPage }: { data?: TransmissionPage; loading: boolean; file: string; setFile: (value: string) => void; setPage: (page: number) => void }) {
  const items = data?.items ?? [];
  const page = data?.page ?? 1;
  const pages = Math.max(1, data?.totalPages ?? 1);
  return <Card className="mb-5 overflow-hidden"><div className="flex flex-wrap items-center gap-3 border-b bg-slate-50 px-5 py-4"><b className="text-sm text-slate-800">Lotes recebidos do Connector</b><input className="rounded border border-slate-300 px-2 py-1 text-sm" value={file} onChange={event => setFile(event.target.value)} placeholder="Filtrar por arquivo SPED importado" /></div>{loading ? <p className="p-5 text-sm text-slate-500">Carregando lotes...</p> : !items.length ? <p className="p-5 text-sm text-slate-500">Nenhum arquivo encontrado.</p> : <><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead><tr className="border-b text-xs uppercase text-slate-500"><th className="p-3">Arquivo / status</th><th className="p-3">Registros</th><th className="p-3">Produto</th><th className="p-3">NCM</th><th className="p-3">CST / CFOP</th></tr></thead><tbody>{items.map(item => <tr className="border-b border-slate-100" key={item.id}><td className="p-3"><b>{item.sourceName || "Carga local"}</b><small className="block">{item.status}{item.sourceSize != null ? ` · ${new Intl.NumberFormat("pt-BR", { style: "unit", unit: "byte", unitDisplay: "narrow" }).format(item.sourceSize)}` : ""}</small></td><td className="p-3">{item.processedRows}/{item.totalRows}</td><td className="p-3">{item.records[0] ? <Link className="text-blue-700 hover:underline" href={`/connector-data/products/${item.records[0].id}?source=connector`}>{item.records[0].canonicalDescription}</Link> : "—"}</td><td className="p-3">{item.records[0]?.ncm || "—"}</td><td className="p-3">{String(item.records[0]?.rawData?.cstIcms ?? "—")} / {String(item.records[0]?.rawData?.cfop ?? "—")}</td></tr>)}</tbody></table></div><div className="flex items-center justify-between p-3 text-sm"><span>{data?.total ?? 0} arquivo(s) · página {page}/{pages}</span><div className="flex gap-2"><button className="rounded border px-2 py-1 disabled:opacity-50" disabled={page === 1} onClick={() => setPage(page - 1)}>Anterior</button><button className="rounded border px-2 py-1 disabled:opacity-50" disabled={page === pages} onClick={() => setPage(page + 1)}>Próxima</button></div></div></>}</Card>;
}
