"use client";

import { useQuery } from "@tanstack/react-query";
import { BellRing, Building2, CheckCircle2, CircleDot, Database, FileCheck2, FileClock, PackageCheck, PlugZap, ShieldCheck } from "lucide-react";
import { Card, ErrorState, PageHeader, dateTime } from "@/components/shared/ui";
import { dashboardService, type ImplementationStage } from "@/services/dashboard.service";

const stageLabel: Record<ImplementationStage, string> = { COMPLETED: "Concluído", IN_PROGRESS: "Em andamento", PENDING: "Pendente", BLOCKED: "Bloqueado" };
const stageStyle: Record<ImplementationStage, string> = { COMPLETED: "bg-emerald-100 text-emerald-800", IN_PROGRESS: "bg-blue-100 text-blue-800", PENDING: "bg-amber-100 text-amber-800", BLOCKED: "bg-red-100 text-red-800" };

export default function Dashboard() {
  const { data, isLoading, isError } = useQuery({ queryKey: ["dashboard", "implementation-summary"], queryFn: dashboardService.summary });
  if (isLoading) return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[1, 2, 3, 4].map((item) => <div key={item} className="h-32 animate-pulse rounded-xl bg-slate-200" />)}</div>;
  if (isError || !data) return <ErrorState />;
  const metrics = [
    { label: "Cadastro do cliente", value: `${data.client.registrationComplete}%`, detail: `${data.client.branches} estabelecimentos`, icon: Building2 },
    { label: "Produtos importados", value: data.products.imported.toLocaleString("pt-BR"), detail: `${data.products.validated.toLocaleString("pt-BR")} validados`, icon: PackageCheck },
    { label: "Tributações validadas", value: data.taxation.validated.toLocaleString("pt-BR"), detail: `${data.taxation.divergent.toLocaleString("pt-BR")} divergências`, icon: ShieldCheck },
    { label: "Método de extração", value: data.extraction.connectorStatus === "ONLINE" ? "Online" : "Offline", detail: data.extraction.method, icon: PlugZap },
  ];
  return <>
    <PageHeader title="Painel de Conciliação" description="Visão cadastral, fiscal e operacional da implantação do cliente." />
    <Card className="mb-5 flex flex-wrap items-center justify-between gap-4 border-cyan-200 bg-cyan-50/50 p-5"><div><p className="text-xs font-semibold uppercase tracking-wide text-cyan-700">Cliente selecionado</p><h2 className="mt-1 text-xl font-bold text-slate-900">{data.client.legalName}</h2><p className="text-sm text-slate-600">{data.client.document}</p></div><div className="text-right text-sm text-slate-600"><p>Última sincronização</p><strong className="text-slate-900">{dateTime(data.extraction.lastSyncAt)}</strong><p>{data.extraction.frequency}</p></div></Card>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{metrics.map(({ label, value, detail, icon: Icon }) => <Card key={label} className="p-5"><div className="mb-4 flex items-center justify-between"><span className="grid size-10 place-items-center rounded-lg bg-cyan-50 text-cyan-700"><Icon size={21} /></span><CircleDot size={16} className="text-emerald-500" /></div><p className="text-2xl font-bold text-slate-900">{value}</p><p className="mt-1 text-sm font-semibold text-slate-700">{label}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></Card>)}</div>
    <div className="mt-5 grid gap-5 xl:grid-cols-3">
      <Card className="p-5"><div className="mb-5 flex items-center gap-3"><Database className="text-cyan-700" /><div><h2 className="font-bold text-slate-900">Qualidade dos dados importados</h2><p className="text-sm text-slate-500">Produtos e tributação recebidos pelo Connector</p></div></div><DataProgress label="Produtos validados" value={data.products.validated} total={data.products.imported} /><DataProgress label="Tributações validadas" value={data.taxation.validated} total={data.taxation.imported} /><div className="mt-4 grid grid-cols-3 gap-3 text-center text-sm"><Summary label="Pendentes" value={data.products.pending} /><Summary label="Rejeitados" value={data.products.rejected} /><Summary label="Divergências fiscais" value={data.taxation.divergent} /></div></Card>
      <Card className="p-5"><div className="mb-5 flex items-center gap-3"><BellRing className="text-cyan-700" /><div><h2 className="font-bold text-slate-900">Automações fiscais</h2><p className="text-sm text-slate-500">Coleta contínua e processamento por evento</p></div></div><Automation label="Monitoramento via API" active={data.monitoring.apiEnabled} detail="Recebimento automático de dados fiscais" /><Automation label="Conexão direta ao banco" active={data.monitoring.directDatabaseEnabled} detail="Coleta agendada pelo Connector" /><Automation label="Novo arquivo SPED" active={data.sped.eventDriven} detail="Processamento iniciado no recebimento" icon="file" /><div className="mt-4 rounded-lg bg-amber-50 p-3"><p className="text-xs font-semibold uppercase text-amber-800">Alertas gerados</p><strong className="mt-1 block text-2xl text-amber-950">{data.monitoring.openAlerts + data.sped.generatedAlerts}</strong><p className="text-xs text-amber-800">{data.monitoring.openAlerts} fiscais · {data.sped.generatedAlerts} do SPED</p></div></Card>
      <Card className="overflow-hidden"><div className="border-b border-slate-200 p-5"><div className="flex items-center gap-3"><FileCheck2 className="text-cyan-700" /><div><h2 className="font-bold text-slate-900">Serviços contratados e implantação</h2><p className="text-sm text-slate-500">Escopo que orienta as rotinas executadas pelo Connector</p></div></div></div><div className="divide-y divide-slate-100">{data.services.map((service) => <div key={service.code} className="flex items-center justify-between gap-3 p-4"><div className="flex items-center gap-3">{service.enabled ? <CheckCircle2 size={18} className="text-emerald-600" /> : <CircleDot size={18} className="text-slate-300" />}<div><p className="text-sm font-semibold text-slate-800">{service.name}</p><p className="text-xs text-slate-500">{service.enabled ? "Serviço contratado" : "Fora do escopo atual"}</p></div></div><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${stageStyle[service.stage]}`}>{stageLabel[service.stage]}</span></div>)}</div></Card>
    </div>
  </>;
}

function DataProgress({ label, value, total }: { label: string; value: number; total: number }) { const percentage = total ? Math.round((value / total) * 100) : 0; return <div className="mb-4"><div className="mb-1 flex justify-between text-sm"><span className="font-semibold text-slate-700">{label}</span><span>{percentage}%</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-emerald-500" style={{ width: `${percentage}%` }} /></div><p className="mt-1 text-xs text-slate-500">{value.toLocaleString("pt-BR")} de {total.toLocaleString("pt-BR")}</p></div>; }
function Summary({ label, value }: { label: string; value: number }) { return <div className="rounded-lg bg-slate-50 p-3"><strong className="block text-lg text-slate-900">{value.toLocaleString("pt-BR")}</strong><span className="text-xs text-slate-500">{label}</span></div>; }
function Automation({ label, active, detail, icon }: { label: string; active: boolean; detail: string; icon?: "file" }) { const Icon = icon === "file" ? FileClock : PlugZap; return <div className="mb-3 flex items-start gap-3 rounded-lg border border-slate-100 p-3"><Icon size={18} className={active ? "text-emerald-600" : "text-slate-400"} /><div><p className="text-sm font-semibold text-slate-800">{label}</p><p className="text-xs text-slate-500">{detail}</p></div><span className={`ml-auto rounded-full px-2 py-0.5 text-[11px] font-semibold ${active ? "bg-emerald-100 text-emerald-800" : "bg-slate-100 text-slate-600"}`}>{active ? "Ativo" : "Inativo"}</span></div>; }
