"use client";
import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Button, Card, ErrorState, PageHeader, StatusBadge } from "@/components/shared/ui";
import { connectorQueriesService, type ConnectorMonitoring, type ConnectorQuery } from "@/services/connector-queries.service";
import { getApiErrorMessage } from "@/services/api/client";

export default function Page() {
  const qc=useQueryClient(), [form,setForm]=useState<ConnectorQuery|null>(null), [initial,setInitial]=useState(false), [sql,setSql]=useState<ConnectorQuery|null>(null);
  const queries=useQuery({queryKey:["connector-queries"],queryFn:connectorQueriesService.list});
  const monitor=useQuery({queryKey:["connector-monitoring"],queryFn:connectorQueriesService.monitoring,refetchInterval:15000});
  const refresh=()=>Promise.all([qc.invalidateQueries({queryKey:["connector-queries"]}),qc.invalidateQueries({queryKey:["connector-monitoring"]})]);
  const toggle=useMutation({mutationFn:({id,enabled}:{id:string;enabled:boolean})=>connectorQueriesService.setEnabled(id,enabled),onSuccess:refresh});
  if(queries.isLoading)return <Card className="p-8">Carregando...</Card>;
  if(queries.isError)return <ErrorState message={getApiErrorMessage(queries.error)}/>;
  return <><PageHeader title="Consultas do Connector" description="Extrações, agendamentos e situação dos envios."/><Operations data={monitor.data} queries={queries.data??[]} initial={()=>setInitial(true)} configure={setForm} refresh={refresh}/>{monitor.isError&&<ErrorState message={getApiErrorMessage(monitor.error)}/>}<Card className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead><tr><th className="p-3 text-left">Consulta</th><th>Versão</th><th>Descrição</th><th>Envio</th><th/></tr></thead><tbody>{queries.data?.map(q=><tr className="border-t" key={q.id}><td className="p-3 font-mono text-xs">{q.code}</td><td>v{q.version}</td><td>{q.description}</td><td><StatusBadge value={q.enabled?"ACTIVE":"INACTIVE"}/></td><td className="flex gap-1 py-2"><Button variant="ghost" onClick={()=>setSql(q)}>SELECT</Button><Button variant={q.enabled?"danger":"secondary"} onClick={()=>toggle.mutate({id:q.id,enabled:!q.enabled})}>{q.enabled?"Desativar":"Ativar"}</Button><Button variant="secondary" disabled={!q.enabled} onClick={()=>setForm(q)}>Configurar</Button></td></tr>)}</tbody></table></Card>{sql&&<Card className="mt-4 p-4"><div className="flex justify-between"><b>{sql.code} v{sql.version}</b><Button variant="ghost" onClick={()=>setSql(null)}>Fechar</Button></div><pre className="mt-3 max-h-[32rem] overflow-auto whitespace-pre rounded bg-slate-950 p-4 text-xs text-white">{sql.sqlPreview}</pre></Card>}{form&&<ScheduleForm query={form} close={()=>{setForm(null);void refresh()}}/>}{initial&&<InitialLoad close={()=>{setInitial(false);void refresh()}}/>}</>;
}

function Operations({data,queries,initial,configure,refresh}:{data?:ConnectorMonitoring;queries:ConnectorQuery[];initial:()=>void;configure:(q:ConnectorQuery)=>void;refresh:()=>void}){
  const [id,setId]=useState(""); const connector=data?.connectors[0]; const online=connector?.lastHeartbeatAt?Date.now()-new Date(connector.lastHeartbeatAt).getTime()<180000:false;
  const toggle=useMutation({mutationFn:({id,active}:{id:string;active:boolean})=>connectorQueriesService.setScheduleActive(id,active),onSuccess:refresh});
  return <Card className="mb-4 border-cyan-200 p-4"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-semibold">Agendamento e envio de dados</h2><p className="text-sm text-slate-600">Configure e acompanhe a extração diretamente no portal.</p></div><div className="flex gap-2"><StatusBadge value={online?"ONLINE":"OFFLINE"}/><Button variant="secondary" onClick={initial}>Carga inicial</Button></div></div><div className="mt-4 grid gap-3 md:grid-cols-3"><Info title="Connector" value={connector?.machineName||"Não conectado"} detail={connector?.lastHeartbeatAt?`Contato: ${new Date(connector.lastHeartbeatAt).toLocaleString("pt-BR")}`:"Sem heartbeat"}/><label className="grid gap-2 rounded border bg-slate-50 p-3 text-sm"><span className="text-xs uppercase text-slate-500">Nova execução</span><select className="rounded border p-2" value={id} onChange={e=>setId(e.target.value)}><option value="">Selecione</option>{queries.filter(q=>q.enabled).map(q=><option key={q.id} value={q.id}>{q.code} v{q.version}</option>)}</select><Button variant="secondary" disabled={!id} onClick={()=>{const q=queries.find(x=>x.id===id);if(q)configure(q)}}>Configurar</Button></label><Info title="Jobs" value={`${data?.jobs.filter(j=>j.status==="PENDING").length??0} pendentes`} detail={`${data?.jobs.filter(j=>j.status==="FAILED").length??0} com falha`}/></div>{data?.schedules.map(s=><div key={s.id} className="mt-3 flex items-center justify-between rounded border p-3 text-sm"><div><b className="font-mono text-xs">{s.queryCode} v{s.queryVersion}</b><p className="text-xs text-slate-500">{s.frequency==="MINUTES"?`A cada ${s.intervalMinutes} min`:s.frequency==="HOURLY"?"A cada hora":"Diário"} · próxima {new Date(s.nextRunAt).toLocaleString("pt-BR")}</p></div><Button variant={s.active?"danger":"secondary"} onClick={()=>toggle.mutate({id:s.id,active:!s.active})}>{s.active?"Pausar":"Ativar"}</Button></div>)}<h3 className="mt-4 text-sm font-semibold">Últimos jobs</h3>{data?.jobs.length?<div className="overflow-x-auto"><table className="mt-2 w-full min-w-[620px] text-xs"><tbody>{data.jobs.slice(0,8).map(j=><tr className="border-t" key={j.id}><td className="p-2 font-mono">{j.queryCode} v{j.queryVersion}</td><td><StatusBadge value={j.status}/></td><td>{new Date(j.requestedAt).toLocaleString("pt-BR")}</td><td>{j.errorMessage||(j.status==="PENDING"?(online?"Aguardando busca automática":"Connector offline"):"—")}</td></tr>)}</tbody></table></div>:<p className="mt-2 text-sm text-slate-500">Nenhum job para o cliente selecionado.</p>}</Card>;
}
function Info({title,value,detail}:{title:string;value:string;detail:string}){return <div className="rounded border bg-slate-50 p-3 text-sm"><p className="text-xs uppercase text-slate-500">{title}</p><b>{value}</b><p className="mt-1 text-xs text-slate-500">{detail}</p></div>}

function Targets({value,set}:{value:string;set:(v:string)=>void}){const q=useQuery({queryKey:["connector-targets"],queryFn:connectorQueriesService.listConnectors});useEffect(()=>{if(!value&&q.data?.length===1)set(q.data[0].connectorId)},[value,q.data,set]);return <select className="rounded border p-2" value={value} onChange={e=>set(e.target.value)}><option value="">Selecione o Connector</option>{q.data?.map(x=><option key={x.connectorId} value={x.connectorId}>{x.machineName||x.connectorId}</option>)}</select>}

function InitialLoad({close}:{close:()=>void}){const [connectorId,setConnectorId]=useState("");const companyId=typeof window==="undefined"?"":localStorage.getItem("concilia_company_id")??"";const run=useMutation({mutationFn:()=>connectorQueriesService.startInitialLoad(connectorId,companyId),onSuccess:close});return <Card className="mt-4 grid gap-3 border-cyan-200 p-4"><b>Carga inicial completa</b><Targets value={connectorId} set={setConnectorId}/>{run.isError&&<ErrorState message={getApiErrorMessage(run.error)}/>}<div><Button disabled={!connectorId||!companyId||run.isPending} onClick={()=>run.mutate()}>Iniciar carga</Button><Button className="ml-2" variant="secondary" onClick={close}>Cancelar</Button></div></Card>}

function ScheduleForm({query,close}:{query:ConnectorQuery;close:()=>void}){const [connectorId,setConnectorId]=useState(""),[repeat,setRepeat]=useState(false),[frequency,setFrequency]=useState<"DAILY"|"HOURLY"|"MINUTES">("DAILY"),[minutes,setMinutes]=useState(60);const d=new Date(Date.now()+300000),[start,setStart]=useState(new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16));const companyId=typeof window==="undefined"?"":localStorage.getItem("concilia_company_id")??"";const save=useMutation({mutationFn:()=>repeat?connectorQueriesService.createRecurringSchedule(query.id,{connectorId,companyId,startAt:new Date(start).toISOString(),frequency,...(frequency==="MINUTES"?{intervalMinutes:minutes}:{})}):connectorQueriesService.schedule(query.id,connectorId,companyId),onSuccess:close});return <Card className="mt-4 grid gap-3 border-cyan-200 p-4"><b>{query.code} v{query.version}</b><Targets value={connectorId} set={setConnectorId}/><label className="flex gap-2 text-sm"><input type="checkbox" checked={repeat} onChange={e=>setRepeat(e.target.checked)}/> Repetir automaticamente</label>{repeat&&<div className="grid gap-3 md:grid-cols-3"><input type="datetime-local" className="rounded border p-2" value={start} onChange={e=>setStart(e.target.value)}/><select className="rounded border p-2" value={frequency} onChange={e=>setFrequency(e.target.value as typeof frequency)}><option value="DAILY">Diária</option><option value="HOURLY">A cada hora</option><option value="MINUTES">Em minutos</option></select>{frequency==="MINUTES"&&<input type="number" min={1} max={1440} className="rounded border p-2" value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/>}</div>}{save.isError&&<ErrorState message={getApiErrorMessage(save.error)}/>}<div><Button disabled={!connectorId||!companyId||save.isPending} onClick={()=>save.mutate()}>{repeat?"Salvar agendamento":"Executar uma vez"}</Button><Button className="ml-2" variant="secondary" onClick={close}>Cancelar</Button></div></Card>}
