"use client";

import { Fragment, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Button, Card, ErrorState, PageHeader, StatusBadge } from "@/components/shared/ui";
import { connectorQueriesService, type ConnectorQuery } from "@/services/connector-queries.service";
import { getApiErrorMessage } from "@/services/api/client";

export default function Page() {
  const queryClient = useQueryClient();
  const [creatingCode, setCreatingCode] = useState<string | null>(null);
  const [selected, setSelected] = useState<ConnectorQuery | null>(null);
  const [scheduling, setScheduling] = useState<ConnectorQuery | null>(null);
  const [initialLoading, setInitialLoading] = useState(false);
  const queries = useQuery({ queryKey: ["connector-queries"], queryFn: connectorQueriesService.list });
  const coverage = useQuery({ queryKey: ["connector-queries","coverage"], queryFn: connectorQueriesService.coverage });
  const refresh = async () => { await Promise.all([queryClient.invalidateQueries({ queryKey: ["connector-queries"] }), queryClient.invalidateQueries({ queryKey: ["connector-queries","coverage"] })]); };
  const toggle = useMutation({ mutationFn: ({ id, enabled }: { id: string; enabled: boolean }) => connectorQueriesService.setEnabled(id, enabled), onSuccess: refresh });
  if (queries.isLoading) return <Card className="p-8">Carregando consultas...</Card>;
  if (queries.isError) return <><PageHeader title="Consultas do Connector" description="Consultas versionadas, somente leitura e auditáveis." /><ErrorState message={getApiErrorMessage(queries.error)} /><div className="mt-3"><Button variant="secondary" onClick={() => queries.refetch()}>Tentar novamente</Button></div></>;
  return <>
    <PageHeader title="Consultas do Connector" description="Consultas versionadas, somente leitura e auditáveis." action={<div className="flex gap-2"><Button variant="secondary" onClick={() => setInitialLoading(true)}>Carga inicial</Button><Button onClick={() => setCreatingCode("")}>Nova consulta</Button></div>} />
    {coverage.data&&<Card className={`mb-4 p-4 ${coverage.data.operationLevelValidationReady?"border-emerald-200 bg-emerald-50":"border-amber-200 bg-amber-50"}`}><div className="flex flex-wrap items-center justify-between gap-2"><div><b className="text-slate-900">Cobertura dos dados fiscais: {coverage.data.coveragePercent}%</b><p className="mt-1 text-sm text-slate-600">{coverage.data.operationLevelValidationReady?"A extração por item fiscal está pronta para validar as operações.":"Falta uma consulta FISCAL_DOCUMENT_ITEMS_V1 ativa, aprovada e com todos os campos obrigatórios."}</p></div><StatusBadge value={coverage.data.ready?"READY":"INCOMPLETE"}/></div>{coverage.data.queries.filter(query=>!query.ready).map(query=><div key={query.code} className="mt-3 flex flex-wrap items-center justify-between gap-3 rounded border border-amber-200 bg-white/70 p-3 text-xs"><div><b className="font-mono text-slate-900">{query.code}</b><span className="ml-2 text-slate-600">{!query.exists?"Consulta não cadastrada":!query.enabled?"Inativa":!query.approvedForConnector?"Não aprovada para o Connector":`Campos obrigatórios ausentes: ${query.missingRequired.join(", ")}`}</span></div>{!query.exists&&<Button variant="secondary" onClick={()=>setCreatingCode(query.code)}>Cadastrar SELECT</Button>}</div>)}</Card>}
    {toggle.isError&&<div className="mb-4"><ErrorState message={getApiErrorMessage(toggle.error)}/></div>}
    <Card className="overflow-x-auto"><table className="w-full min-w-[820px] text-sm"><thead className="bg-slate-50"><tr><th className="p-3 text-left">Código</th><th>Versão</th><th>Descrição</th><th className="p-3 text-left">Envio ao Connector</th><th /></tr></thead><tbody>{queries.data?.map((item) => <Fragment key={item.id}><tr className="border-t"><td className="p-3 font-mono text-xs">{item.code}</td><td>v{item.version}</td><td>{item.description}</td><td className="p-3"><div className="flex items-center gap-2"><StatusBadge value={item.enabled ? "ACTIVE" : "INACTIVE"}/><Button variant={item.enabled?"danger":"secondary"} disabled={toggle.isPending} onClick={()=>toggle.mutate({id:item.id,enabled:!item.enabled})}>{item.enabled?"Desativar":"Ativar"}</Button></div></td><td className="flex gap-1 py-3"><Button variant="ghost" onClick={()=>setSelected(selected?.id===item.id?null:item)}>{selected?.id===item.id?"Ocultar SELECT":"Visualizar SELECT"}</Button><Button disabled={!item.enabled} variant="secondary" onClick={()=>setScheduling(item)}>Agendar</Button></td></tr>{selected?.id===item.id&&<tr className="border-t bg-slate-950"><td colSpan={5} className="p-4"><div className="mb-3 flex items-center justify-between gap-3 text-white"><b>{item.code} v{item.version}</b><span className="font-mono text-[10px] text-slate-400">SHA-256: {item.sha256}</span></div><pre className="max-h-[32rem] overflow-auto whitespace-pre rounded bg-slate-900 p-4 text-xs leading-5 text-slate-100">{item.sqlPreview}</pre></td></tr>}</Fragment>)}{queries.data?.length===0&&<tr><td colSpan={5} className="p-10 text-center text-sm text-slate-500">Nenhuma consulta foi cadastrada para o tenant selecionado. Consulte o tenant da sessão ou publique as definições neste ambiente.</td></tr>}</tbody></table></Card>
    {creatingCode !== null && <DefinitionForm initialCode={creatingCode} close={() => setCreatingCode(null)} refresh={refresh} />}
    {scheduling && <ScheduleForm query={scheduling} close={() => setScheduling(null)} />}
    {initialLoading && <InitialLoadForm close={() => setInitialLoading(false)} />}
  </>;
}

function InitialLoadForm({ close }: { close: () => void }) {
  const targets = useQuery({ queryKey: ["connector-targets"], queryFn: connectorQueriesService.listConnectors });
  const [connectorId, setConnectorId] = useState("");
  const [result, setResult] = useState<{ scheduledJobs: number } | null>(null);
  const companyId = typeof window === "undefined" ? "" : localStorage.getItem("concilia_company_id") ?? "";
  const start = useMutation({ mutationFn: () => connectorQueriesService.startInitialLoad(connectorId, companyId), onSuccess: (response: any) => setResult(response?.data ?? response) });
  return <Card className="mt-4 grid gap-3 p-4"><div><p className="font-medium">Carga inicial completa</p><p className="mt-1 text-sm text-slate-500">Cria um job para cada consulta ativa liberada ao cliente. O Connector sincroniza, consulta o Oracle e envia os lotes automaticamente.</p></div><label className="grid gap-1 text-sm font-medium text-slate-700">Connector<select className="rounded border p-2 font-mono text-sm font-normal" value={connectorId} onChange={(event) => setConnectorId(event.target.value)}><option value="">Selecione o Connector</option>{targets.data?.map((target) => <option key={target.connectorId} value={target.connectorId}>{target.machineName || "Connector"} — {target.connectorId}</option>)}</select></label>{!companyId&&<p className="text-sm text-amber-700">Selecione um cliente no cabeçalho antes de iniciar.</p>}{start.isError&&<p className="text-sm text-red-700">{getApiErrorMessage(start.error)}</p>}{result&&<p className="rounded bg-emerald-50 p-3 text-sm text-emerald-800">Carga iniciada: {result.scheduledJobs} consulta(s) colocada(s) na fila.</p>}<div>{!result&&<Button disabled={!connectorId || !companyId || start.isPending} onClick={() => start.mutate()}>{start.isPending ? "Iniciando..." : "Iniciar carga inicial"}</Button>}<Button className={result ? "" : "ml-2"} variant="secondary" onClick={close}>{result ? "Fechar" : "Cancelar"}</Button></div></Card>;
}

function DefinitionForm({ initialCode, close, refresh }: { initialCode: string; close: () => void; refresh: () => void }) {
  const [code, setCode] = useState(initialCode); const [description, setDescription] = useState(""); const [sqlPreview, setSql] = useState("SELECT\n  ...\nFROM CONSINCO...");
  const create = useMutation({ mutationFn: () => connectorQueriesService.create({ code, description, sqlPreview, parameters: [], timeoutSeconds: 60, maxRows: 10000, batchSize: 500 }), onSuccess: () => { refresh(); close(); } });
  return <Card className="mt-4 grid gap-3 p-4"><input className="rounded border p-2 font-mono" placeholder="FISCAL_DOCUMENTS" value={code} onChange={(event) => setCode(event.target.value.toUpperCase())} /><input className="rounded border p-2" placeholder="Descrição" value={description} onChange={(event) => setDescription(event.target.value)} /><textarea className="min-h-52 rounded border p-3 font-mono text-xs" value={sqlPreview} onChange={(event) => setSql(event.target.value)} /><div><Button disabled={!code || !description || create.isPending} onClick={() => create.mutate()}>Publicar versão</Button><Button className="ml-2" variant="secondary" onClick={close}>Cancelar</Button></div></Card>;
}

function ScheduleForm({ query, close }: { query: ConnectorQuery; close: () => void }) {
  const targets = useQuery({ queryKey: ["connector-targets"], queryFn: connectorQueriesService.listConnectors });
  const [connectorId, setConnectorId] = useState("");
  const companyId = typeof window === "undefined" ? "" : localStorage.getItem("concilia_company_id") ?? "";
  const schedule = useMutation({ mutationFn: () => connectorQueriesService.schedule(query.id, connectorId, companyId), onSuccess: close });
  return <Card className="mt-4 grid gap-3 p-4"><div><p className="font-medium">Agendar extração: {query.code} v{query.version}</p><p className="mt-1 text-sm text-slate-500">O job fica vinculado ao tenant, ao cliente selecionado e ao Connector.</p></div><label className="grid gap-1 text-sm font-medium text-slate-700">Connector e ID<select className="rounded border p-2 font-mono text-sm font-normal" value={connectorId} onChange={(event) => setConnectorId(event.target.value)}><option value="">Selecione o Connector</option>{targets.data?.map((target) => <option key={target.connectorId} value={target.connectorId}>{target.machineName || "Connector"} — {target.connectorId}{target.environment ? ` (${target.environment})` : ""}</option>)}</select></label>{!companyId&&<p className="text-sm text-amber-700">Selecione um cliente no cabeçalho antes de agendar.</p>}{connectorId && <p className="rounded bg-cyan-50 p-3 text-sm text-cyan-950">ConnectorId que receberá o job: <code className="font-semibold">{connectorId}</code></p>}{targets.data?.length === 0 && <p className="text-sm text-amber-700">Nenhum Connector ativo reportou presença para esta empresa.</p>}{schedule.isError && <p className="text-sm text-red-700">{getApiErrorMessage(schedule.error)}</p>}<div><Button disabled={!connectorId || !companyId || schedule.isPending} onClick={() => schedule.mutate()}>{schedule.isPending ? "Agendando..." : "Agendar extração"}</Button><Button className="ml-2" variant="secondary" onClick={close}>Cancelar</Button></div></Card>;
}
